CREATE TABLE CUSTOMERS (
  IDE_CUSTOMER BIGINT      NOT NULL PRIMARY KEY,
  F_NAME       VARCHAR(50) NOT NULL,
  L_NAME       VARCHAR(50) NOT NULL
);

/* Sequences */
CREATE SEQUENCE S_CUSTOMER
  START WITH 1
  INCREMENT BY 1;